# Generated by Django 2.0 on 2019-11-04 11:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('league_name', models.CharField(blank=True, max_length=15, null=True, verbose_name='加盟姓名')),
                ('league_moblie', models.CharField(blank=True, max_length=11, null=True, verbose_name='加盟号码')),
                ('message', models.TextField(blank=True, max_length=200, null=True, verbose_name='内容')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '招商加盟',
                'verbose_name_plural': '招商加盟',
            },
        ),
    ]
