# Generated by Django 2.0 on 2019-11-04 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='名称')),
                ('address', models.CharField(max_length=50, verbose_name='地址')),
                ('phone', models.CharField(max_length=15, verbose_name='电话')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '联系我们',
                'verbose_name_plural': '联系我们',
            },
        ),
    ]
