# Generated by Django 2.0 on 2019-11-04 11:48

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PrivateRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='包房名')),
                ('number', models.CharField(max_length=15, verbose_name='人数')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '包房型',
                'verbose_name_plural': '包房型',
            },
        ),
        migrations.CreateModel(
            name='RoomDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime.now, verbose_name='日期')),
            ],
            options={
                'verbose_name': '包房日期',
                'verbose_name_plural': '包房日期',
            },
        ),
        migrations.AddField(
            model_name='privateroom',
            name='room_date',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooms.RoomDate', verbose_name='包房日期'),
        ),
    ]
